graph LR
    RHG["Royal Horse Guards (RHG)"] -->|1969| RHGD
    LG["Life Guards (LG)"] -->|1992| HCR
    1D["1st (Royal) Dragoons (1D)"] -->|1969| RHGD
    1DG["1st (King's) Dragoon Guards (1DG)"] -->|1959| QDG
    3DG["3rd (Prince of Wales') Dragoon Guards (3DG)"] -->|1922| 3C
    4DG["4th (Royal Irish) Dragoon Guards (4DG)"] -->|1922| 47DG
    6DG["Carabiniers (6th Dragoon Guards) (6DG)"] -->|1922| 3C
    7DG["7th (The Princess Royal's) Dragoon Guards (7DG)"] -->|1922| 47DG
    5L["5th Royal Irish Lancers (5L)"] -->|1922| 165L
    6D["6th (Inniskilling) Dragoons (6D)"] -->|1922| 5IDG
    9L["9th (Queen's Royal) Lancers (9L)"] -->|1960| 912L
    11H["11th (Prince Albert's Own) Hussars (11H)"] -->|1969| RH
    15H["15th (The King's) Hussars (15H)"] -->|1922| 1519H
    16L["16th Lancers (16L)"] -->|1922| 165L
    17L["17th (Duke of Cambridge's Own) Lancers (17L)"] -->|1922| 1721L
    20H["20th Hussars (20H)"] -->|1922| 1420H
    21L["21st (Empress of India's) Lancers (21L)"] -->|1922| 1721L
    3C["3rd Carabiniers (Prince of Wales's Dragoon Guards) (3C)"] -->|1971| SDG
    47DG["4th/7th Royal Dragoon Guards (4/7DG)"] -->|1992| RDG
    5IDG["5th Royal Inniskilling Dragoon Guards (5 INNIS DG)"] -->|1992| RDG
    1318H["13th/18th Royal Hussars (Queen Mary's Own) (13/18 RH)"] -->|1992| LD
    1420H["14th/20th King's Hussars (14/20H)"] -->|1992| KRH
    1519H["15th/19th The King's Royal Hussars (15/19H)"] -->|1992| LD
    165L["16th/5th The Queen's Royal Lancers (16/5L)"] -->|1993| QRL
    1721L["17th/21st Lancers (17/21L)"] -->|1993| QRL
    QOH["Queen's Own Hussars (QOH)"] -->|1993| QRH
    QRIH["Queen's Own Royal Irish Hussars (QRIH)"] -->|1993| QRH
    QDG["1st The Queen's Dragoon Guards (QDG)"]
    912L["9th/12th Royal Lancers (9/12L)"] -->|2015| RL
    RHGD["Blues and Royals (Royal Horse Guards and 1st Dragoons) (RHG/D)"] -->|1992| HCR
    RH["The Royal Hussars (Prince of Wales's Own) (RH)"] -->|1992| KRH
    SDG["Royal Scots Dragoon Guards (Carabiniers and Greys) (SCOTS DG)"]
    HCR["Household Cavalry Regiment (HCR)"]
    KRH["King's Royal Hussars (KRH)"]
    LD["Light Dragoons (LD)"]
    RDG["Royal Dragoon Guards (RDG)"]
    QRH["Queen's Royal Hussars (QRH)"]
    QRL["Queen's Royal Lancers (QRL)"] -->|2015| RL
    RL["Royal Lancers (RL)"]
